INSERT INTO brand (name)
SELECT * FROM (SELECT 'ACV') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'ACV') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'AGROTK') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'AGROTK') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'BOBCAT') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'BOBCAT') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'BULMOR') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'BULMOR') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'CASE') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'CASE') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'CATERPILAR') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'CATERPILAR') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'CHALLENGER') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'CHALLENGER') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'CROWN') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'CROWN') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'DEUTZ FAHR') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'DEUTZ FAHR') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'DOOSAN') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'DOOSAN') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'GEHL') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'GEHL') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'GENIE') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'GENIE') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'HAULOTTE') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'HAULOTTE') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'HITACHI') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'HITACHI') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'HYSTER') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'HYSTER') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'GCV') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'GCV') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'JLG') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'JLG') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'JOHN GEERE') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'JOHN GEERE') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'KOBELCO') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'KOBELCO') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'KONATSU') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'KONATSU') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'KUBOTA') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'KUBOTA') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'LIEBHERR') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'LIEBHERR') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'MASSEY FERGUSON') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'MASSEY FERGUSON') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'NEW HOLLAND') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'NEW HOLLAND') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'RAYCO') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'RAYCO') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'SANY') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'SANY') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'SKY JACK') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'SKY JACK') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'SKY TRAK') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'SKY TRAK') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'TAKEUCHI') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'TAKEUCHI') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'TIGERCAT') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'TIGERCAT') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'TOYOTA') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'TOYOTA') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'UNICARRIERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'UNICARRIERS') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'VERNEER') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'VERNEER') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'VOLVO') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'VOLVO') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'WACKER NEUSON') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'WACKER NEUSON') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'YALE') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'YALE') LIMIT 1;

INSERT INTO brand (name)
SELECT * FROM (SELECT 'YANMAR') AS tmp
WHERE NOT EXISTS (SELECT name FROM brand WHERE name = 'YANMAR') LIMIT 1;