INSERT INTO category (name)
SELECT * FROM (SELECT 'COMPACT TRACK LOADERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'COMPACT TRACK LOADERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'SKIDDERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'SKIDDERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'DRUM COMPACTORS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'DRUM COMPACTORS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'ACKHOE LOADERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'ACKHOE LOADERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'BOOM LIFTS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'BOOM LIFTS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'BULLDOZERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'BULLDOZERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'COMBINES') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'COMBINES') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'FORESTRY EQUIPMENTS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'FORESTRY EQUIPMENTS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'FORK LIFTS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'FORK LIFTS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'MOWER WINDROWERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'MOWER WINDROWERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'MULCHERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'MULCHERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'SCISSOR LIFTS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'SCISSOR LIFTS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'SKID STEER LOADERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'SKID STEER LOADERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'TELEHAND LERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'TELEHAND LERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'TRACKTORS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'TRACKTORS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'WHEEL LOADERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'WHEEL LOADERS') LIMIT 1;

INSERT INTO category (name)
SELECT * FROM (SELECT 'WOOD CHIPPERS') AS tmp
WHERE NOT EXISTS (SELECT name FROM category WHERE name = 'WOOD CHIPPERS') LIMIT 1;