"""Models updated + Models added

Revision ID: c487d987d3a8
Revises: 115756301a55
Create Date: 2025-03-04 13:44:22.581684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c487d987d3a8'
down_revision = '115756301a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_products',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('cart_id', 'product_id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cart_product_id_fkey', 'product', ['product_id'], ['id'])

    op.drop_table('cart_products')
    # ### end Alembic commands ###
