"""Models updated + Models added

Revision ID: d45ab71b5d06
Revises: c487d987d3a8
Create Date: 2025-03-04 13:48:06.410540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45ab71b5d06'
down_revision = 'c487d987d3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_products')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('cart_products',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='cart_products_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='cart_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name='cart_products_pkey')
    )
    op.drop_table('cart_item')
    # ### end Alembic commands ###
